### PR TITLE
Add optional module for Jakarta Transactions impl of Jakarta EE 9 Spec

### LINKED ISSUE #26041: Transition from Jakarta EE 8 to Jakarta EE 9
## Feature Request

**For English only**, other languages will not be accepted.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

No

### Describe the feature you would like.

After Jakarta EE 9 has been released, The group id `javax-***` is no longer maintained, it would be a good idea to migrate `javax` to `jakarta` namespace.

The following GAVs are mentioned in shardingsphere:

```xml
<dependency>
    <groupId>javax.transaction</groupId>
    <artifactId>jta</artifactId>
</dependency>
<dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>javax.annotation-api</artifactId>
</dependency>
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
</dependency>
<dependency>
    <groupId>javax.activation</groupId>
    <artifactId>javax.activation-api</artifactId>
</dependency>
```

Here is the latest version until May 30th, 2023:

```xml
<dependency>
    <groupId>jakarta.transaction</groupId>
    <artifactId>jakarta.transaction-api</artifactId>
    <version>2.0.1</version>
</dependency>
<dependency>
    <groupId>jakarta.annotation</groupId>
    <artifactId>jakarta.annotation-api</artifactId>
    <version>2.1.1</version>
</dependency>
<dependency>
    <groupId>jakarta.xml.bind</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>4.0.0</version>
</dependency>
<dependency>
    <groupId>jakarta.activation</groupId>
    <artifactId>jakarta.activation-api</artifactId>
    <version>2.1.2</version>
</dependency>
```

Refs:
[Jakarta EE Maven Coordinates](https://wiki.eclipse.org/Jakarta_EE_Maven_Coordinates)
[Transition from Java EE to Jakarta EE](https://blogs.oracle.com/javamagazine/post/transition-from-java-ee-to-jakarta-ee)
[Javax to Jakarta Namespace Ecosystem Progress](https://jakarta.ee/blogs/javax-jakartaee-namespace-ecosystem-progress/)

### PR DESCRIPTION
**Pull request by linghengqian**
Fixes #26041 .

Changes proposed in this pull request:
  - Add optional module for Jakarta Transactions impl of Jakarta EE 9 Spec.
  - Compared to the reverted PR https://github.com/apache/shardingsphere/pull/35810, this PR updates `org.eclipse.transformer:transformer-maven-plugin:0.5.0` to `org.eclipse.transformer:transformer-maven-plugin:1.0.0`. 
  - The prerequisite PR is https://github.com/apache/shardingsphere/pull/39758 .

---

Before committing this PR, I'm sure that I have checked the following options:
- [x] My code follows the [code of conduct](https://shardingsphere.apache.org/community/en/involved/conduct/code/) of this project.
- [x] I have self-reviewed the commit code.
- [x] I have (or in comment I request) added corresponding labels for the pull request.
- [x] I have passed maven check locally : `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e`.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding unit tests for my changes.
- [x] I have updated the Release Notes of the current development version. For more details, see [Update Release Note](https://shardingsphere.apache.org/community/en/involved/contribute/contributor/)
- [ ] I have disclosed the tool and affected files or scope for any material AI assistance, as required by the [AI-assisted contribution policy].

[AI-assisted contribution policy]: https://github.com/apache/shardingsphere/blob/master/AI_POLICY.md

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
### Result

**Review Result: Not Mergeable**

Feedback Mode: Change Request

**Blocking Issues: 2**

The transformed artifacts work in isolation, but the documented Proxy configuration creates an incompatible mixed Jakarta/Javax classpath. The new integration tests also violate mandatory repository coding standards.

### Blocking Issues

1. **The Proxy migration recipe retains the legacy XA provider**

   - **Evidence:** The new recipes in `docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/jakarta-transactions/_index.en.md:158` and `_index.cn.md:152` exclude only `shardingsphere-transaction-xa-core` and add the Jakarta modules. However, `distribution/proxy/pom.xml:242` activates `default-dep` by default, which independently adds the legacy `shardingsphere-transaction-xa-atomikos` at line 291. The `all`, `transaction-atomikos`, and `transaction-narayana` profiles likewise retain legacy providers. A reproduction of this documented mixed classpath failed while loading the provider with `ServiceConfigurationError`, caused by `NoClassDefFoundError: javax/transaction/SystemException`.
   - **Impact:** Proxy binaries or containers built from the documented procedure cannot reliably load the XA provider. The same classpath contains duplicate provider/SPI classes compiled against incompatible `javax.transaction` and `jakarta.transaction` contracts.
   - **Required Change:** Update the Proxy procedure or provide a dedicated Maven profile that replaces—not supplements—the legacy XA core, SPI, and provider dependencies. Verify the resulting Proxy classpath and startup with both Atomikos and Narayana.

2. **The four transformation integration tests violate mandatory Java standards**

   - **Evidence:** In all four `JakartaNamespaceTransformationIT` files, lines 55–58 declare `List<byte[]> classBytes`, although only `Collection` operations are used; the asserted value lacks the required `actual` prefix; and the 172-character reconstructed statement is unnecessarily wrapped. Line 75 also names a method parameter `entry`, which is prohibited without a contract fixing that name:
     - `kernel/transaction/type/xa-jakarta/core/src/test/java/org/apache/shardingsphere/transaction/xa/jakarta/core/JakartaNamespaceTransformationIT.java`
     - `kernel/transaction/type/xa-jakarta/spi/src/test/java/org/apache/shardingsphere/transaction/xa/jakarta/spi/JakartaNamespaceTransformationIT.java`
     - `kernel/transaction/type/xa-jakarta/provider/atomikos/src/test/java/org/apache/shardingsphere/transaction/xa/jakarta/atomikos/JakartaNamespaceTransformationIT.java`
     - `kernel/transaction/type/xa-jakarta/provider/narayana/src/test/java/org/apache/shardingsphere/transaction/xa/jakarta/narayana/JakartaNamespaceTransformationIT.java`
   - **Impact:** The added tests do not satisfy the repository’s collection-declaration, test-value naming, parameter naming, and line-wrapping requirements. These semantic rules are not fully enforced by Checkstyle or Spotless.
   - **Required Change:** Correct the shared test implementation in all four modules—for example, use `Collection<byte[]> actualClassBytes`, keep the qualifying statement on one line, and rename the helper parameter to `jarEntry`.

### Coverage

- **Candidate:** Public PR #39881, code-correctness review only.
- **Head:** `f77f1310374dfb8a2537d4f306a98ce4f2d6d2e1`
- **Base:** `master` at `fdd58d899c30e92e02edd947b5a5ddaedc64da6f`
- The latest-head check and authoritative 17-file GitHub inventory were unchanged at convergence.
- Reviewed behavior clusters:
  - Reactor and transformer-plugin configuration.
  - Generated Jakarta SPI, Atomikos, Narayana, core, sources, and service descriptors.
  - Namespace-transformation integration tests.
  - JDBC/Proxy usage documentation and release notes.
- Runtime verification:
  - `./mvnw -pl kernel/transaction/type/xa-jakarta/spi,kernel/transaction/type/xa-jakarta/provider/atomikos,kernel/transaction/type/xa-jakarta/provider/narayana,kernel/transaction/type/xa-jakarta/core -am -Dspotless.skip=true -Dmaven.javadoc.skip=true -Djacoco.skip=true verify -B -T1C` — exit 0.
  - All four new integration tests passed.
  - Isolated transformed Atomikos and Narayana providers initialized successfully.
  - Generated jars retained `javax.transaction.xa` while converting Jakarta Transactions references and preserving service descriptors.
- Mandatory style verification:
  - Combined exact-file `spotless:check checkstyle:check -Pcheck -T1C` over the eight owning Maven projects — exit 0.
  - Spotless selected and passed all 8 changed POMs and all 4 changed Java files.
  - Checkstyle selected and passed all 4 changed Java files with zero violations.
  - Spotless was not applicable to the five changed Markdown files because repository configuration governs Java, POM, and GitHub workflow files.
  - Checkstyle was not applicable to the eight POMs or five Markdown files because repository configuration governs Java source and test trees.
- All 17 authoritative files were accounted for across root-cause, blast-radius/contracts, and tests/runtime/operations passes. No unresolved evidence gaps remain.
- CI and GitHub Actions were not reviewed; this result is code-scope only.

**Review by linghengqian — COMMENTED** [review]
- Everything has been resolved. As for the SS Proxy, I don't think there's much to be done regarding the actual profile, since it involves dependency exclusions—something unlikely to be accomplished before the Maven 4 release. I simply updated the documentation.

**Review by terrymanu — CHANGES_REQUESTED** [review]
### Result

**Review Result: Not Mergeable**

Feedback Mode: Change Request

**Blocking Issues: 3**

The Jakarta transformation itself builds and passes its focused tests, and the previous Java-style findings are fixed. Three documentation and release-contract issues remain.

### Blocking Issues

1. **The new published modules are missing from `shardingsphere-bom`.**

   - **Evidence:** ShardingSphere documents that its BOM contains version information for all modules and lets consumers omit individual versions ([BOM contract](https://github.com/apache/shardingsphere/blob/d94a0660e76e5939e7a9ec3c0b746337f0b06d02/docs/document/content/user-manual/dependencies/bom.en.md#L7-L11)). The BOM manages the four legacy XA artifacts ([`bom/pom.xml`](https://github.com/apache/shardingsphere/blob/d94a0660e76e5939e7a9ec3c0b746337f0b06d02/bom/pom.xml#L793-L812)), but an exact artifact-ID search confirmed that it does not manage the new `shardingsphere-transaction-xa-jakarta-spi`, `-core`, `-atomikos`, or `-narayana` JARs.
   - **Impact:** A consumer importing `shardingsphere-bom` cannot declare any of these new public modules without supplying its own version, violating the documented BOM contract and producing a missing-dependency-version Maven model error when the version is omitted.
   - **Required Change:** Add all four new JAR artifacts to `bom/pom.xml` dependency management with `${project.version}`.

2. **The Proxy instructions do not provide a build path that actually avoids the legacy providers.**

   - **Evidence:** The new instructions modify only the top-level bootstrap dependency and then say not to activate `default-dep`, `all`, or either transaction profile ([English documentation](https://github.com/apache/shardingsphere/blob/d94a0660e76e5939e7a9ec3c0b746337f0b06d02/docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/jakarta-transactions/_index.en.md#L152-L216)). However, `default-dep` is `activeByDefault` and directly adds the legacy Atomikos artifact ([Proxy POM](https://github.com/apache/shardingsphere/blob/d94a0660e76e5939e7a9ec3c0b746337f0b06d02/distribution/proxy/pom.xml#L241-L294)); the established full-build command activates `all` ([contributor guide](https://github.com/apache/shardingsphere/blob/d94a0660e76e5939e7a9ec3c0b746337f0b06d02/docs/community/content/involved/contribute/contributor.en.md#L39-L44)), which directly adds both legacy providers ([Proxy POM](https://github.com/apache/shardingsphere/blob/d94a0660e76e5939e7a9ec3c0b746337f0b06d02/distribution/proxy/pom.xml#L469-L498)). Local `help:active-profiles` verification confirmed `default-dep` for the default invocation and `all` for `-P-dev,release,all`. Maven requires another same-POM profile or explicit profile deactivation to suppress an `activeByDefault` profile ([Maven profile activation](https://maven.apache.org/guides/introduction/introduction-to-profiles.html#details-on-profile-activation)).
   - **Impact:** Following the POM edit and running Maven normally still adds the legacy provider, while following the standard build command adds both legacy providers. This recreates the mixed `javax.transaction`/`jakarta.transaction` classpath and startup failure that the warning describes.
   - **Required Change:** Document an exact, verified binary and container build invocation that explicitly deactivates `default-dep` and does not activate `all` or the legacy transaction profiles. Verify that the resulting Proxy classpath contains only the selected Jakarta provider and that Proxy starts successfully.

3. **Both new Narayana sections identify Narayana configuration as Atomikos configuration.**

   - **Evidence:** The English section says “Atomikos configuration items” while referring to `shardingsphere-transaction-xa-narayana`, `jbossts-properties.xml`, and Narayana’s `CoreEnvironmentBean.nodeIdentifier` ([English lines 106–112](https://github.com/apache/shardingsphere/blob/d94a0660e76e5939e7a9ec3c0b746337f0b06d02/docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/jakarta-transactions/_index.en.md#L106-L112)). The Chinese page contains the same incorrect provider name ([Chinese lines 104–109](https://github.com/apache/shardingsphere/blob/d94a0660e76e5939e7a9ec3c0b746337f0b06d02/docs/document/content/user-manual/shardingsphere-jdbc/optional-plugins/jakarta-transactions/_index.cn.md#L104-L109)).
   - **Impact:** The user-facing configuration guide incorrectly attributes Narayana’s configuration file and property to Atomikos.
   - **Required Change:** Replace “Atomikos” with “Narayana” in both localized sections.

### Evidence

- Reviewed public PR [#39881](https://github.com/apache/shardingsphere/pull/39881) at exact head `d94a0660e76e5939e7a9ec3c0b746337f0b06d02`; a final freshness check confirmed the head and 17-file scope were unchanged.
- The Eclipse Transformer `1.0.0` `jar` goal and `jakartaDefaults` configuration match the version-specific [official plugin documentation](https://github.com/eclipse-transformer/transformer/blob/1.0.0/maven-plugins/transformer-maven-plugin/README.md).
- Focused reactor verification passed with exit code 0:

  `./mvnw -pl kernel/transaction/type/xa-jakarta/spi,kernel/transaction/type/xa-jakarta/provider/atomikos,kernel/transaction/type/xa-jakarta/provider/narayana,kernel/transaction/type/xa-jakarta/core -am -Dspotless.skip=true -Dmaven.javadoc.skip=true -Djacoco.skip=true verify -B -T1C`

- All four `JakartaNamespaceTransformationIT` tests ran successfully. Generated JAR inspection confirmed Jakarta transaction references while preserving `javax.transaction.xa`.
- ServiceLoader smoke tests instantiated and closed the transformed Atomikos provider and initialized/stopped the transformed Narayana provider successfully.

### Coverage

- **Focus:** Code Correctness Review; this result is code-scope only. GitHub Actions and CI state were not queried or reviewed.
- **Candidate:** Public PR head `d94a0660e76e5939e7a9ec3c0b746337f0b06d02`; base and merge-base `42d2ad1cbbd59ed6a8f917c6e4322a02a91e5db5`.
- **Requirements:** PR description, linked issue [#26041](https://github.com/apache/shardingsphere/issues/26041), current review discussion, repository module/BOM contracts, and current Maven/Transformer behavior.
- **Authoritative files:** All 17 files were accounted for: `RELEASE-NOTES.md`; four English/Chinese Jakarta and Spring Boot documentation files; root, transaction-type, and six `xa-jakarta` POMs; and four namespace transformation integration tests.
- **Behavior clusters:** reactor/module registration; Transformer-generated SPI, core, Atomikos, and Narayana artifacts; service registration and provider initialization; namespace tests; JDBC/Proxy installation guidance; release notes; public BOM and distribution compatibility.
- **Discovery lenses completed:** root cause and behavior; blast radius and contracts; tests, runtime, and operations. The final convergence pass produced no additional independent candidates. No outcome-sensitive evidence gap remains.
- **Local style verification:** Exact-head snapshot, exit code 0:

  `./mvnw -X -pl ':shardingsphere,:shardingsphere-transaction-type,:shardingsphere-transaction-xa-jakarta,:shardingsphere-transaction-xa-jakarta-core,:shardingsphere-transaction-xa-jakarta-spi,:shardingsphere-transaction-xa-jakarta-provider,:shardingsphere-transaction-xa-jakarta-atomikos,:shardingsphere-transaction-xa-jakarta-narayana' -DspotlessFiles='<exact filters for the 8 changed POMs and 4 changed Java files>' -Dcheckstyle.includes='org/apache/shardingsphere/transaction/xa/jakarta/core/JakartaNamespaceTransformationIT.java,org/apache/shardingsphere/transaction/xa/jakarta/spi/JakartaNamespaceTransformationIT.java,org/apache/shardingsphere/transaction/xa/jakarta/atomikos/JakartaNamespaceTransformationIT.java,org/apache/shardingsphere/transaction/xa/jakarta/narayana/JakartaNamespaceTransformationIT.java' -Dcheckstyle.includeResources=false -Dcheckstyle.includeTestResources=false spotless:check checkstyle:check -Pcheck -T1C`

  Spotless covered all eight changed POMs and all four changed Java files. Checkstyle covered all four changed Java files, one per owning test source root. Checkstyle is not applicable to the changed POMs under the repository’s source/test configuration; the five changed Markdown files are not governed by either configured check.

**Review by linghengqian — COMMENTED** [review]
I opened https://github.com/apache/shardingsphere/pull/39913 to fix the E2E tests.

**Review by linghengqian — COMMENTED** [review]
Resolved; it mainly involved documentation updates.

**Review by terrymanu — APPROVED** [review]
### Result

**Review Result: Mergeable**

The optional Jakarta XA modules are correctly wired and packaged for the reviewed code scope. No blocking code or documentation issue is confirmed.

### Evidence

- The four Jakarta modules built successfully, and all four namespace integration tests passed.
- Generated JARs use Jakarta transaction types, retain the JDK’s `javax.transaction.xa` types, and contain the expected service descriptors.
- The documented regular Proxy build profile disables the legacy default provider.

### Coverage

- Public PR [#39881](https://github.com/apache/shardingsphere/pull/39881), head `cbe8c2b17fb0bc0655436b33523071a9d969ded2`, base `7e2dae148026f83b0108b0b1c9ae085c41dae4de`. All 18 authoritative changed files were reviewed: nine POMs, four Java integration tests, and five Markdown files.
- Reactor wiring, BOM entries, transformed artifacts, tests, JDBC and Proxy instructions, and release notes were covered. Root-cause, contract, runtime, and final convergence passes found no unresolved blocker.
- Local `spotless:check checkstyle:check -Pcheck` across the nine owning Maven projects exited 0, covering every changed POM and Java file. Checkstyle does not govern POMs or Markdown; Spotless does not govern the changed Markdown files.
- Focused reactor `verify` for all four Jakarta modules exited 0. This is a **code-scope conclusion**; CI was not reviewed.
- Jev skill was not used because this required repository-wide code and contract analysis. Jev MCP was not called because quota was unconfirmed (0 calls); it did not affect the review. Efficiency change cannot be measured accurately; no Jev-related problems were found.
